name: "my-work-action"
author: "inkblotty"
description: "Action to summarize all the work you've done in a week for you into a PR"
inputs:
  owner:
    description: "The owner of the repo where the PR should be created."
    required: true
  queried_repos:
    description: "The repos that should be searched for relevant work, comma-separated."
    required: true
  repo:
    description: "The name of the repo where the PR should be created."
    required: true
  timespan:
    description: "Number of days to query, with today as the end date. Defaults to 7 days."
    required: false
  usernames:
    description: "Your user handle, or your list of teammates, comma-separated."
    required: true
  project_field:
    description: "A project field to display for issues and pull requests"
    required: false
  destination_branch:
    description: "The branch for a PR to be created against. Defaults to 'main'."
    required: false
  draft_pr:
    description: "Whether to create the PR as a draft. Defaults to true."
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
