name: "my-work-action"
author: "inkblotty"
description: "Action to summarize all the work you've done in a week for you into a PR"
inputs:
  output_repo:
    description: "The repo where the PR should be created."
    required: true
  usernames:
    description: "Your user handle, or your list of teammates, comma-separated."
    required: true
  timespan:
    description: "Number of days to query, with today as the end date. Defaults to 7 days."
    required: false
  focused_orgs:
    description: "The orgs that should be searched for relevant work, comma-separated."
    required: false
  focused_repos: string;
    description: "The repos that should be searched for relevant work, comma-separated."
    required: false
  excluded_repos:
    description: "The repos that should be exluded from the output, comma-separated."
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
